name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Docker
      uses: docker/setup-buildx-action@v1

    - name: Run Docker container
      run: |
        docker run -d -p ${{ secrets.DOCKER_PORTS_BACKEND }} ${{ secrets.DOCKER_IMAGE_BACKEND }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Dependencies
      run: |
        npm install axios mocha moralis ethers
        npm install chai@4.3.4
        
    - name: Run Tests
      env:
        API_KEY: ${{ secrets.API_KEY }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        MORALIS_API_KEY: ${{ secrets.MORALIS_API_KEY }}
      run: npx mocha