name: Manual Workflow

on:
    workflow_dispatch:
        inputs:
            image-backend:
                description: 'Docker image backend'
                required: true
            image-backend-ports:
                description: 'Ports for image backend'
                required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Docker
      run: |
        sudo apt-get remove docker docker-engine docker.io containerd runc
        sudo apt-get update
        sudo apt-get install apt-transport-https ca-certificates curl software-properties-common
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        sudo apt-get update
        sudo apt-get install docker-ce docker-ce-cli containerd.io

    - name: Run Docker container
      run: |
        echo "image-backend: ${{ github.event.inputs.image-backend }}"
        echo "image-backend-ports: ${{ github.event.inputs.image-backend-ports }}"
        docker run -d -p ${{ github.event.inputs.image-backend-ports }} ${{ github.event.inputs.image-backend }}

    - name: Install Dependencies
      run: |
        sudo apt-get install -y nodejs npm
        npm install axios mocha moralis ethers
        npm install chai@4.3.4

    - name: Run Tests
      env:
        API_KEY: ${{ secrets.API_KEY }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        MORALIS_API_KEY: ${{ secrets.MORALIS_API_KEY }}
      run: npx mocha