name: Manual Workflow

on:
    workflow_dispatch:
        inputs:
            image-backend:
                description: 'Docker image backend'
                required: true
            image-backend-ports:
                description: 'Ports for image backend'
                required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Docker
      uses: docker-practice/actions-setup-docker@master

    - name: Run Docker container
      run: |
        echo "image-backend: ${{ github.event.inputs.image-backend }}"
        echo "image-backend-ports: ${{ github.event.inputs.image-backend-ports }}"
        docker run -d -p ${{ github.event.inputs.image-backend-ports }} ${{ github.event.inputs.image-backend }}

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Dependencies
      run: |
        npm install axios mocha moralis ethers
        npm install chai@4.3.4

    - name: Run Tests
      env:
        API_KEY: ${{ secrets.API_KEY }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        MORALIS_API_KEY: ${{ secrets.MORALIS_API_KEY }}
      run: npx mocha